//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dastan {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Dastan.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: {0}.
        /// </summary>
        internal static string ERROR_MESSAGE {
            get {
                return ResourceManager.GetString("ERROR_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execution Error.
        /// </summary>
        internal static string EXECUTION_ERROR {
            get {
                return ResourceManager.GetString("EXECUTION_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export completed!
        ///File: {0}
        ///
        ///.
        /// </summary>
        internal static string EXPORT_COMPLETED_DESCRIPTION {
            get {
                return ResourceManager.GetString("EXPORT_COMPLETED_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Complete.
        /// </summary>
        internal static string EXPORT_COMPLETED_TITLE {
            get {
                return ResourceManager.GetString("EXPORT_COMPLETED_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Selection.
        /// </summary>
        internal static string INVALID_SELECTION {
            get {
                return ResourceManager.GetString("INVALID_SELECTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select an Element in the Project Browser first..
        /// </summary>
        internal static string NO_ELEMENT_SELECTED_ERROR {
            get {
                return ResourceManager.GetString("NO_ELEMENT_SELECTED_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select  the default output folder.
        /// </summary>
        internal static string NULL_OUTPUT_DIRECTORY_ERROR_MSG {
            get {
                return ResourceManager.GetString("NULL_OUTPUT_DIRECTORY_ERROR_MSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select output directory.
        /// </summary>
        internal static string SELECT_OUTPUT_DIRECTORY {
            get {
                return ResourceManager.GetString("SELECT_OUTPUT_DIRECTORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate Label for UI Components.
        /// </summary>
        internal static string SETTINGS_UI_LABEL_GENERATE {
            get {
                return ResourceManager.GetString("SETTINGS_UI_LABEL_GENERATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate Tooltip for UI Components.
        /// </summary>
        internal static string SETTINGS_UI_TOOLTIP_GENERATE {
            get {
                return ResourceManager.GetString("SETTINGS_UI_TOOLTIP_GENERATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a StateMachine element in the Project Browser first..
        /// </summary>
        internal static string STATE_MACHINE_NOT_SELECTED_ERROR {
            get {
                return ResourceManager.GetString("STATE_MACHINE_NOT_SELECTED_ERROR", resourceCulture);
            }
        }
    }
}
